version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_DB=db
     - POSTGRES_USER=username
     - POSTGRES_PASSWORD=password123
